### ISSUE TITLE
Setting up a build config 

### ISSUE THREAD

**Issue by deecewan** [Brisbane-React-JS/meetups#11]
Sorting out webpack 2 and babel with various plugins is a big job and scares off a lot of people,who resort to Creat React App. This limits freedom and choice. 

I'd be happy to present how I set up my build config, what tools I use, etc. 

This would include a full dev environment, including hot module replacement with the new react hot loader.

**Comment by patrickgordon** [comment]
+1 this would be awesome. Will take a fair bit of time I'd think. Maybe best broken over two meetup?

**Comment by deecewan** [comment]
nah, super quick.  set up config. explain what everything does.  15, 20 minutesish.

**Comment by kzima** [comment]
@deecewan, I am happy to schedule 20mins for the next meetup in April. Would that be ok?

**Comment by deecewan** [comment]
perfect.
