### ISSUE TITLE
Semantic Redux for state management 

### ISSUE THREAD

**Issue by deecewan** [Brisbane-React-JS/meetups#12]
A brief walk through of redux, using it with your application, and how to do async in a clean, semantic way. Touch on best practice with regard to connecting with react-redux

**Comment by kzima** [comment]
@deecewan, Redux and async stuff sounds like great topic. Would you like to give a talk about it on the next meetup?

**Comment by deecewan** [comment]
@kzima like, the one on Monday?

**Comment by kzima** [comment]
@deecewan, Lets push this one to May 👍

**Comment by iamtommcc** [comment]
@deecewan Are you still doing this talk for the June meetup? Was going to volunteer a Redux talk but if you're still doing this one I'll hold off as we'd cover a lot of the same ground 👌

**Comment by deecewan** [comment]
you go for it. i'm keen to hear other thoughts on it.
