### ISSUE TITLE
React in your Brownfields Project

### ISSUE THREAD

**Issue by loklaan** [Brisbane-React-JS/meetups#14]
Hey folks,

There is a talk I have in mind for relaying the challenges and wins of integrating React (web) into an existing project.

It would largely cover:

* Why you might want to bring React into an existing (brownfields/legacy/old/large) application
* The challenges you're probably going to encounter
* Expect to gain some big 'wins' - but not straight away

Happy to take questions in here, and bring the answers for them into the talk.

**Comment by patrickgordon** [comment]
:+1: Interested in this.

**Comment by kzima** [comment]
Can't wait to hear more about it!
