### ISSUE TITLE
The state of Styling in React

### ISSUE THREAD

**Issue by loklaan** [Brisbane-React-JS/meetups#16]
Hey folks, 

The ecosystem around styling in React and React Native is still fairly turbulent. I'd like to talk about the concerns around styling for web/native, and the current solutions floating about.

**Comment by patrickgordon** [comment]
styled-components
css modules
BEM

Any others?

**Comment by kzima** [comment]
@loklaan, I can book you for 10min (max 5 slides) for the next meetup on May 22nd. Would that be ok with you?

**Comment by loklaan** [comment]
@kzima Yup, let's do it. Might go over 5 slides ;)

**Comment by kzima** [comment]
you negotiate hard! ok, lest settle on 6 slides :)
