### ISSUE TITLE
Reselect in action

### ISSUE THREAD

**Issue by kzima** [Brisbane-React-JS/meetups#17]
This talk was volunteered by @patrickgordon.

**Comment by loklaan** [comment]
I see what you did there. 😏

**Comment by patrickgordon** [comment]
Here's the slides:
https://docs.google.com/presentation/d/1giiD_CpPeg3PD6XuRJXCuM6l_ye1mXfLbdW8GHQbQXA/edit?usp=sharing

Here's the gists of the sample files:
https://gist.github.com/patrickgordon/a38ee732ad5b1d92f03a82c4c8403a27

**Comment by kzima** [comment]
@patrickgordon, thanks Patrick!
