### ISSUE TITLE
Tooling niceness. Embedding the GraphiQL query builder into my React client.

### ISSUE THREAD

**Issue by triyuga** [Brisbane-React-JS/meetups#19]
If you do Apps that use APIs and micro-services, and you don’t use GraphQL , slap yourself now and start using GraphQL. Its awesome!

**Comment by loklaan** [comment]
There are a couple typo's in the description. :wink: 

Are you primarily going to be talking about & showing off Apollo?

I think that covering GraphQL from other perspectives, like designing an API around it, might be out of scope for the meetup audience.

**Comment by jwulf** [comment]
*typos

**Comment by jwulf** [comment]
Switching your React app to Apollo, with a brief overview of GraphQL and the server-side. We'll be talking about the incremental approach to weaning yourself off the past and onto the future - how to architect your React app in such a way that you can transition incrementally from legacy architectures like Redux.

**Comment by loklaan** [comment]
I think GraphQL is great.

Sounds like you want to cover:
* an overview of graphql
* writing a graphql api
* an overview of apollo
* architecting a react application (around apollo?)
* replacing other modern data layers (with apollo?)

I would recommend limited the scope of the talk though, as you'd be lucky to adequately explain all that even if you were given 2 hours.

I'm not discouraging anyone from talking about stuff, just trying to point out that the scope of this is too big.

For example, no one has yet presented singularly on React application architectures, Redux or GraphQL (server-side concerns / client-side concerns). So, that stuff may be better to present on initially!

**Comment by triyuga** [comment]
Thanks for the feedback guys. I agree 100% @loklaan my initial description has a vague and untenable scope.

I've spent the last couple of weeks setting up a GraphQL backend for Magikcraft, as the basis for developing our React Client V2 against. I'm really pleased with GraphQL, but this is a React meetup!

So, here is a more targeted topic:

# Tooling niceness. Embedding the GraphiQL query builder into my React client.

**Comment by triyuga** [comment]
Hi @kzima just letting you know I've changed/narrowed the topic for this talk proposal. Previously it was **React with GraphQL and Apollo. You're welcome!**

The new topic about Graphiql UI in React is of much smaller scope, and could work as a 10-15 min talk.

**Comment by triyuga** [comment]
Talk outline:

- What is GraphQL and what is Graphiql? (brief, like 3 mins)
- Demo setting up the GraphiQL react component in an existing project
- A note about authentication
- Look at how nice the GqphQL schema is to work with :)

**Comment by kzima** [comment]
@triyuga, I am going to book 10 min for you (max 5 slides) for Monday 22nd. Would that be fine with you?

**Comment by triyuga** [comment]
@kzima sure!
