### ISSUE TITLE
Intro to React VR

### ISSUE THREAD

**Issue by bakkerme** [Brisbane-React-JS/meetups#21]
There's a lot of excitement around React VR since it just hit v1.0, so I figure it would make a good talk topic. I've been experimenting with it so consider me a volunteer.

My thinking here is:
- What it is and how it works
- Getting started
- A demo of some of the things you can do

**Comment by kzima** [comment]
@bakkerme Would you like dive into this topic and give a quick talk?

**Comment by bakkerme** [comment]
For sure, should make for an exciting topic.

**Comment by kzima** [comment]
Awesome!

**Comment by kzima** [comment]
@bakkerme, Just checking if May 22nd ok for you to give an intro into VR? I can book you for 10min (max 5 slides).

**Comment by bakkerme** [comment]
@kzima Sounds good, I can work with 10 min. Cheers!
