### ISSUE TITLE
Real-world Redux

### ISSUE THREAD

**Issue by iamtommcc** [Brisbane-React-JS/meetups#22]
- Basic overview of the benefits Redux provides for those unfamiliar with it
- Best practices & strategies for implementing within a React context: how to make it scale & how to make it help instead of hinder you.
- Go over some common abstractions & libraries to help avoid "death by boilerplate"

Can be either 10 or 20 mins, might be a bit better as a 20 though.

**Comment by kzima** [comment]
@iamtommcc, thanks for volunteering. I will book you for 20 mins :)

**Comment by deecewan** [comment]
i am super keen for this talk.
