### ISSUE TITLE
React first impressions when coming from jQuery

### ISSUE THREAD

**Issue by ghiculescu** [Brisbane-React-JS/meetups#23]
I've been writing jquery professionally for about 5 years. We recently went all in on React - initially on new codebases, and now we're bringing it into our core codebase too.

If anyone's interested I'd be happy to do a talk about first impressions, learning curve, etc.

**Comment by kzima** [comment]
@ghiculescu, It's great to hear other companies are following suit by switching to React. I will chat you about it on Monday and maybe we can schedule a talk for the next meetups.

**Comment by kzima** [comment]
@ghiculescu I had few people looking forward to your speech but you were away at the time. If you still wish to give a talk on our next meetup please let me know.

**Comment by ghiculescu** [comment]
Oh man, sorry, I totally forgot to tell you I'd be out of down.

What would the dates for the August/September meetups be?

**Comment by kzima** [comment]
@ghiculescu, I got a spot reserved for you for the next meetup on August 21st. Would you be available then?

**Comment by ghiculescu** [comment]
Sorry, I will be out of town :( I'm the worst for continuously doing this to you.

I really should be here for the September one!

**Comment by kzima** [comment]
ok, September one is on Monday 18th. Would this suit you better?

**Comment by kzima** [comment]
@ghiculescu should I schedule you for a quick presentation this month?

**Comment by ghiculescu** [comment]
Yep, can do!

**Comment by kzima** [comment]
awesome! I will book you in for Monday 18th then.

**Comment by kzima** [comment]
@ghiculescu Just want to confirm that you are ok for tomorrow?
