### ISSUE TITLE
Universal React & Redux using cookies for persistence and store hydration

### ISSUE THREAD

**Issue by patrickgordon** [Brisbane-React-JS/meetups#26]
I would like to present on how at Jumbo we have approached using cookies to hydrate our store for our Universal web app.

Somewhat of an "advanced" topic, so cognizant that it might not apply to a wider audience.

**Comment by kzima** [comment]
I am going to miss this talk but looking forward to some slides after I am back +1

**Comment by patrickgordon** [comment]
Hey @kzima can we push this to another meetup? I would be keen to talk about redux-cache at the August meetup if possible

**Comment by patrickgordon** [comment]
See #30

**Comment by kzima** [comment]
ok, cool, thanks @patrickgordon

**Comment by patrickgordon** [comment]
lol @ my title for this talk. smh
