### ISSUE TITLE
React Hardware

### ISSUE THREAD

**Issue by bakkerme** [Brisbane-React-JS/meetups#29]
I'm volunteering for a talk on React Hardware, a React system that allows you to control electronic components on an Arduino board. I'll be showing off some simple circuits and how they work with React Hardware and do all the things we know and love about React. I've got a couple of other ideas for demonstrating unusual applications of React's tech so let's call this the official start of a series of talks.

**Comment by patrickgordon** [comment]
Sounds interesting

**Comment by kzima** [comment]
@bakkerme I remember that you needed more time to prepare for this talk. Would you be ready to present it in September's meetup?

**Comment by bakkerme** [comment]
Yeah I'd love too. Count me in.

**Comment by kzima** [comment]
ok, cool. Thanks @bakkerme
