### ISSUE TITLE
Managing complexity and performance with React and Redux

### ISSUE THREAD

**Issue by benoneal** [Brisbane-React-JS/meetups#32]
I'd like to give a talk in November covering design patterns and strategies to manage application complexity and view performance with high throughput interactive interfaces.

**Comment by kzima** [comment]
@benoneal, That would be great! I am looking for speakers for this month. Would you like to present anything on Monday 18th?

**Comment by benoneal** [comment]
@kzima I could potentially run through the ins and outs of server-side rendering?

**Comment by kzima** [comment]
@benoneal That would be great. I will book you in then for 15 min slot.

**Comment by benoneal** [comment]
Just pinging to see if we can confirm this for November?

**Comment by kzima** [comment]
@benoneal Sorry, I missed you message somehow. I am happy to book 20min for you next Monday. Would that be alright?

**Comment by iamtommcc** [comment]
Hey @benoneal, would you be keen to do this talk at the January meetup?

**Comment by benoneal** [comment]
Just getting back into things after a nice holiday. Might have to push this off till Feb.

**Comment by iamtommcc** [comment]
Too easy @benoneal, just let me know if you're still keen & I will lock you in for Feb :)

**Comment by benoneal** [comment]
Yeah I'm down.

**Comment by benoneal** [comment]
[Slides for the presentation](https://docs.google.com/presentation/d/17msHHAMpEgogm3oo-nM-uBLNFMMPuUniQ2vU0Sg6Lqw/edit?usp=sharing)
