### ISSUE TITLE
Static Analysis/Typed JS with React

### ISSUE THREAD

**Issue by deecewan** [Brisbane-React-JS/meetups#33]
Flow and ESLint make a great combination for verifying code before it even gets out the door.

I'd be happy to do a talk on my Flow and ESLint, and how I use them with React/Redux.

**Comment by kzima** [comment]
@deecewan, Are you good for the next meetup?

**Comment by kzima** [comment]
Hey @deecewan, would you be able to give a talk on Monday, October 23rd?

**Comment by deecewan** [comment]
hey @kzima I'm not sure I can get a good talk done by that time unfortunately.

**Comment by deecewan** [comment]
@kzima if i could get a slightly longer slot for this one, that'd be great. 25-30 minutes would be 👌 .

**Comment by kzima** [comment]
ok, cool, Thanks for letting me know. We should be fine with 25min :)

**Comment by kzima** [comment]
@deecewan, great talk on Monday. Do you have any resources you could share on the [meetup page](https://www.meetup.com/Brisbane-ReactJS-Meetup/events/243910349/)?
