### ISSUE TITLE
D3 + React a prototyping story

### ISSUE THREAD

**Issue by ridget** [Brisbane-React-JS/meetups#36]
I almost exclusively work in Ruby and Elixir and yet found myself staring down the barrel of D3, React and a deadline recently. This is a story of how you can use React to replace the `enter()`, `update()` pattern in D3, and make charting super simple. We'll also take a look at how D3 works along the way.

Request: I'm super keen to give this talk, but my twins aren't typically in bed until 6:30 at the latest, meaning I wouldn't be able to talk until 7pm, would this be an issue?

**Comment by patrickgordon** [comment]
Would love to see you there @ridget !

**Comment by kzima** [comment]
@ridget, no problems! 7pm will work fine. I will confirm the date soon. It would be either this month or next month. Would that be ok?

**Comment by ridget** [comment]
@kzima I'm potentially down in Melb next month around the time of the meetup, but nothing confirmed yet (depends on family coverage + coworkers). Even if neither month works out for you, happy to return another month :)

**Comment by kzima** [comment]
ok, I will book you for 10-15min presentation for this month, as I didn't get the confirmation from my last speaker. See you on Monday 23rd.

**Comment by ridget** [comment]
@kzima awesome. Can you confirm if your screen supports widescreen or 4:3 ratio for the slides, and if you have usb-c adapters or what adapters are needed (first Bris React meetup so not sure of what you have on deck :) )

**Comment by kzima** [comment]
@ridget I think the projector supports widescreen and 4:3 and u can connect with it using standard HDMI input cable.

**Comment by kzima** [comment]
Please call me when you arrive as the lift needa card access. My mobile is on the meetup page.

**Comment by kzima** [comment]
@ridget, great talk on Monday. Do you have any resources you could share on the [meetup page](https://www.meetup.com/Brisbane-ReactJS-Meetup/events/243910349/)?

**Comment by ridget** [comment]
Thanks again for having me @kzima! I've posted a comment on the meetup page and have pushed the source code up from the talk here: https://github.com/ridget/react-d3-demo
