### ISSUE TITLE
Basics of performance and the chrome performance panel

### ISSUE THREAD

**Issue by AaronW9090** [Brisbane-React-JS/meetups#39]
Volunteering a quick talk on the basics of rendering performance (with a small touch of javascript performance) as well as a shallow look into the chrome performance panel.

**Comment by kzima** [comment]
@AaronW9090, are you good to present on Monday 20th?

**Comment by AaronW9090** [comment]
Yep this should be good to go

**Comment by kzima** [comment]
awesome!

**Comment by kzima** [comment]
Hi @AaronW9090, 

Thanks for the presentation. It was really informative! I was wondering if you could share your slides on the meetup page?
