### ISSUE TITLE
React Native - introduction

### ISSUE THREAD

**Issue by kzima** [Brisbane-React-JS/meetups#5]

**Comment by MrCeleryman** [comment]
Hi Kris, I messaged you before and I am back from holidays now so happy to talk about my experiences with React Native in a workplace and maybe show how easy it is to get up and running? Never done a talk before so may need some guidance in that aspect...

**Comment by kzima** [comment]
hey @MrCeleryman , What I found works is if you talk about your experience. Just 1-3 slides (problem-solution works great) plus some live coding ideally. No need to be an expert, just share what you know :)
