### ISSUE TITLE
Seeking a great React developer

### ISSUE THREAD

**Issue by liammclennan** [Brisbane-React-JS/meetups#6]
_Kris suggested posting jobs here, so..._

Senior Software Engineer - Web
===============

Startsat60.com is now the largest mature digital and social media site in the world providing the market entry point for our latest venture, Travel at 60, which is set to disrupt the way baby boomers research and purchase travel. We are building an agile, high-performance delivery team to support the rapid expansion of the business into new markets.

Together we will build beautiful, intelligent software that delights. You will help to set the technical direction and have everything you need to do your best work.

**Role responsibilities**

* Design and deliver quality software solutions
* Work with the user experience and visual design team to create amazing user interfaces
* Share your knowledge with other team members while maintaining an open mind and willingness to learn
* Find solutions to multiple technical challenges
* Build scalable and reliable applications that can handle millions of users

**Skills & experience**

* Real world experience delivering complex web applications.
* JavaScript or Typescript and front-end development skills using React, Angular, Elm or similar
* Skill with one or more server technologies such as F#, Scala, Go, Elixir, Node.js or C#
* The ability to learn our business, understand our strategic plan and translate it into valuable software assets
* Attention to detail and the ability to stick with things until they are done.
* Build automation and DevOps (AWS or similar)

Starts at 60 is a friendly, dynamic and exciting startup looking for someone who wants to make a difference. Please send your application to cto@startsat60.com

**Comment by kzima** [comment]
@liammclennan, Please reopen if still available.
