### ISSUE TITLE
Curious little hack. Building a Matrix backdrop in React.

### ISSUE THREAD

**Issue by triyuga** [Brisbane-React-JS/meetups#8]
A short talk about building a simple React UI component: an animated Matrix backdrop. An introductory level talk. 

- Prototyping quickly with /create-react-app 
- Using this.state and simple JS timers to produce animations
- Adding completed MatrixBackdrop component to an existing project

**Comment by triyuga** [comment]
Note: I'm away for the March 20 event but will be available for the next one.

**Comment by triyuga** [comment]
<img width="1440" alt="react-matrix-bg" src="https://cloud.githubusercontent.com/assets/2193454/23853444/6515ef8a-0838-11e7-8192-e8b65c3074b5.png">

**Comment by triyuga** [comment]
https://github.com/triyuga/react-matrix-bg/blob/master/README.md

**Comment by kzima** [comment]
@triyuga Sounds really good. I will book you in for the next talk on 17th of March.

**Comment by kzima** [comment]
@triyuga I booked you in for the next meetup https://www.meetup.com/Brisbane-ReactJS-Meetup/events/238979178/. Please let me know if 10mins + q&a is enough?

**Comment by triyuga** [comment]
@kzima that should be fine!
